(()=>{
'use strict';
const D=window.STELLARIS_DATA,$=id=>document.getElementById(id),state={currency:'USD',current:0,search:'',majorOnly:false};
const esc=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const money=(raw,currency=state.currency)=>{const c=D.currencies[currency],value=raw/c.divisor;return `${c.symbol}${value.toLocaleString(undefined,{minimumFractionDigits:c.decimals,maximumFractionDigits:c.decimals})}`};
const points=value=>Number(value||0).toLocaleString();
const rewardGlyph={Appearance:'♛',Dish:'♨',Relic:'◈','Relic shard':'✦','Relic material':'✦',Badge:'◆',Fantomon:'♜',Material:'⬡',Gift:'🎁',Item:'✧'};
const rewards=(items,core=false)=>`<div class="reward-list">${items.map(item=>`<article class="reward-chip ${core?'core':''} ${item.kind==='Appearance'?'appearance':''}" data-quality="${esc(item.quality)}">${item.webIcon?`<img class="reward-icon" src="assets/item_${item.id}.webp" alt="">`:`<span class="reward-glyph" aria-hidden="true">${rewardGlyph[item.kind]||'✧'}</span>`}<span class="reward-copy"><span class="reward-title">${esc(item.name)} <b>×${points(item.amount)}</b></span><small>${esc(item.kind||'Item')} · ${esc(item.quality||'Unrated')}</small>${item.description?`<span class="reward-desc">${esc(item.description)}</span>`:''}</span></article>`).join('')}</div>`;

function filteredTiers(){return D.tiers.filter(tier=>{if(state.majorOnly&&!tier.major)return false;if(!state.search)return true;return [...tier.core,...tier.extras].some(item=>`${item.name} ${item.description} ${item.id}`.toLowerCase().includes(state.search))})}
function renderSummary(){const next=D.tiers.find(tier=>tier.thresholds[state.currency]>state.current),last=D.tiers[D.tiers.length-1];$('summaryCurrent').textContent=points(state.current);$('summaryNext').textContent=next?`Level ${next.level}`:'Track complete';const remaining=next?next.thresholds[state.currency]-state.current:0;$('summaryRemaining').textContent=points(remaining);$('summarySpend').textContent=money(remaining);const c=D.currencies[state.currency];$('currencyNote').innerHTML=`<b>${esc(c.label)}:</b> thresholds use the client’s configured ${state.currency} scale. ${state.currency==='USD'?'USD uses 100 Stellaris points per $1, so 500 points is approximately $5.00.':'The displayed threshold and price use whole regional currency units.'} The current v${D.configVersion} client table ends at <b>${points(last.thresholds[state.currency])} points (${money(last.thresholds[state.currency])})</b>.`}
function renderRows(){const tiers=filteredTiers(),next=D.tiers.find(tier=>tier.thresholds[state.currency]>state.current);$('resultCount').textContent=`${tiers.length} of ${D.tiers.length} milestones`;$('rewardRows').innerHTML=tiers.map(tier=>{const threshold=tier.thresholds[state.currency],previous=tier.level===1?0:D.tiers[tier.level-2].thresholds[state.currency],remaining=Math.max(0,threshold-state.current),classes=[tier.major?'major':'',threshold<=state.current?'reached':'',next?.level===tier.level?'next':''].filter(Boolean).join(' ');return `<tr class="${classes}"><td class="level-cell"><b>${tier.level}</b><small>Group ${tier.group}${tier.major?' · Major':''}</small></td><td class="points-cell"><b>${points(threshold)}</b><small>cumulative</small></td><td class="price-cell"><b>${money(threshold)}</b><small>approximate</small></td><td class="price-cell"><b>+${money(threshold-previous)}</b><small>+${points(threshold-previous)} pts</small></td><td>${rewards(tier.core,true)}</td><td>${rewards(tier.extras)}</td><td class="remaining ${remaining===0?'done':''}">${remaining===0?'✓ Reached':`<strong>${points(remaining)} pts</strong>${money(remaining)} more`}</td></tr>`}).join('')||'<tr><td colspan="7">No milestones match this filter.</td></tr>'}
function render(){renderSummary();renderRows()}
$('currency').innerHTML=Object.entries(D.currencies).map(([code,c])=>`<option value="${code}">${code} · ${esc(c.label)}</option>`).join('');
$('currency').onchange=e=>{state.currency=e.target.value;render()};$('currentPoints').oninput=e=>{state.current=Math.max(0,Math.floor(+e.target.value||0));render()};$('rewardSearch').oninput=e=>{state.search=e.target.value.trim().toLowerCase();renderRows()};$('majorOnly').onchange=e=>{state.majorOnly=e.target.checked;renderRows()};render();
})();
